project:
  type: website
  output-dir: docs

website:
  title: "sanounawon.github.io"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Qui suis-je ?
      - href: competences.qmd
        text: Compétences
      - href: experiences.qmd
        text: Expériences
      - href: dsprojects.qmd
        text: Data Science | Projets
      - contact.qmd
    tools:
      - icon: github
        menu:
          - text: "Scikit-learn"
            href: https://scikit-learn.org/stable/
          - text: "Projets Python"
            href: https://github.com/sanounawon/DataScience/tree/main/Projects_Python
          - text: "Projets R"
            href: https://github.com/sanounawon/DataScience/tree/main/Projects_R
          


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



