---
title: "Compétences"
---

## Data Science

-   Programmation : Python (NumPy, Pandas, Matplotlib/Seaborn/Plotly, Scikit-learn), R (Tidyverse, Tidymodels), SQL
-   Pipeline de traitements : collecte, nettoyage ;
-   Exploration de données : analyses univariée et bivariée, statistiques inférentielles ;
-   Machine learning :
    -   Modélisation descriptive : analyse factorielle (ACP, ACM, AFDM), classification (K-Means, CAH) ;
    -   Modélisation prédictive : régression linéaire/logistique, arbres de décision, forêts aléatoires, Bagging, Boosting ;
    -   Mise en production : Shiny, Streamlit, FastAPI/Flask.
-   Deep Learning, Text Mining : TensorFlow, Keras, PyTorch, transformers (Hugging Face) ;
-   Big data processing avec Spark ;
-   Outils : Google Cloud Platform (AirFlow, BigQuery), Jupyter, RStudio, Power BI, Git, Excel.

## Base de données

-   Base de données SQL - administration et exploitation sous Microsoft SQL Server, Oracle, MySQL, PostgreSQL ;
-   Base de données NoSQL et calcul distribué avec Docker, MongoDB, Cassandra, CouchDB, ElasticSearch, Spark, Flink.

## Télécoms

-   Architectures Cœur de réseaux 2G/3G/4G/5G ;
-   Protocoles DIAMETER / SIGTRAN / SS7
-   Formations professionnelles :
    -   Le système 5G de bout en bout : architecture, procédures, et interfonctionnement avec la 4G \| *Juin 2022, EFORT - Vélizy-Villacoublay ;*
    -   Réseau Coeur 5G \| *Novembre 2020, EFORT - Vélizy-Villacoublay ;*
    -   Cisco Certified Network Associate Routing & Switching (CCNA) \| *Août 2017, Global Knowledge - Rueil-Malmaison.*

## Gestion de projet

-   Gestion des services informatiques
    -   Certifié **ITIL V4 - Foundation** \| *Juillet 2021, AXELOS - Paris*
-   Coordination de projet
    -   Certifié **PRINCE2 - Foundation** \| *Octobre 2019, AXELOS - Paris*

## Langues

-   Anglais : technique et professionnel

------------------------------------------------------------------------
