---
title: "Expériences"
---

## Ingénieur - Chef de Projet Signalisation et Messaging

**01/2022 - 02/2024 \| ORANGE France - Arcueil**

<li>Mise en œuvre d'un canal bidirectionnel pour l'échange de sms entre clients mobiles et marques avec résolution de portabilité des numéros de marques ;</li>

<li>Upgrade EPAP et STP ;</li>

<li>Intégration aux STP des MVNOs, vTAS, vHLR, SMSF ;</li>

<li>SMS Interworking et coordination SMS jour de l'an ;</li>

<li>Gestion des tranches mobiles.</li>

<li>Environnement technique : SMSC, EPAP/SRF et systèmes périphériques ;</li>

<li>Outils : Anritsu, Wireshark, Business Tools, Grafana, NOE, SWAN.</li>

## Ingénieur Coeur Data Mobile

**01/2018 - 01/2022 \| BOUYGUES TELECOMS - Meudon**

<li>Intégration SGSN-MME Ericsson (Virtual et BareMetal) ;</li>

<li>Déploiement de SPGWs Cisco et définition de la stratégie de mise en service ;</li>

<li>Rédaction HLD/LLD et suivi des évolutions d'outils ;</li>

<li>Suivi et analyse du trafic data APN Grand Public ;</li>

<li>Environnement technique : (v)SGSN-MME, (v)SPGW, et systèmes périphériques.</li>

<li>Outils : Grafana, Bogedo, Node, Frontlinker, Front IP, Loop.</li>

## Ingénieur Exploitation Coeur Voix et Data

**10/2011 - 01/2018 \| NOKIA - Nozay-Villarceaux**

<li>Gestion du catalogue de services et opérations Coeur et Data : client Bouygues Telecoms ;</li>

<li>Suivi et support aux opérations Coeur ;</li>

<li>Projets réalisés : Intégration MSS - MSB - RNC/BSC IP, Migration A TDM en IP, Migration IuCS ATM en IP ;</li>

<li>Environnement technique : équipements Ericsson et NSN (TSC, MSC-S, MSC BC, MGW, HLR, HLRV, FNR, PTS, SGSN, MME, OSS-RC).</li>

<li>Outils : Winfiol, Citrix, Node Manager, M-MGW Network Element Manager, Business Objects, Zabbix, Bogedo, Gepetto, USS (GIR, GCR, ...).</li>

## Support Coeur Voix

**10/2007 - 10/2010 \| ETISALAT - BÉNIN**

<li>Exploitation et maintenance cœur de réseau NGN ;</li>

<li>Assurer la disponibilité des services voix, sms et roaming ;</li>

<li>Environnement technique : équipements Ericsson (MSC, MSC-S, MGW, HLR, CGSN, OSS-RC), VERAZ (I-GATE 4000 EDGE), Analyseur de protocoles TEKTRONIX K18 .</li>

<li>Outils : Winfiol, Citrix, Node Manager, Business Objects .</li>

------------------------------------------------------------------------
